{let equipments = [
    {
        "id": 1,
        "machine": "3 Ton Forklift",
        "regNo": "61979",
        "coc": "YES",
        "brand": "HELI",
        "year": 2015,
        "istimaraExpiry": "8/12/2025",
        "insuranceExpiry": "8/23/2025",
        "tpcExpiry": "3/18/2025",
        "certificationBody": " "
    },
    {
        "id": 2,
        "machine": "3 Ton Forklift",
        "regNo": "43095",
        "coc": "YES",
        "brand": "HELI",
        "year": 2017,
        "istimaraExpiry": "2/15/2026",
        "insuranceExpiry": "3/3/2026",
        "tpcExpiry": "9/17/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 3,
        "machine": "3 Ton Forklift",
        "regNo": "43097",
        "coc": "YES",
        "brand": "HELI",
        "year": 2017,
        "istimaraExpiry": "2/15/2026",
        "insuranceExpiry": "3/3/2026",
        "tpcExpiry": "3/13/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 4,
        "machine": "3 Ton Forklift",
        "regNo": "70579",
        "coc": "YES",
        "brand": "HELI",
        "year": 2021,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "6/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 5,
        "machine": "3 Ton Forklift",
        "regNo": "72871",
        "coc": "YES",
        "brand": "LONKING",
        "year": 2022,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/2/2025",
        "tpcExpiry": "5/27/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 6,
        "machine": "3 Ton Forklift",
        "regNo": "72870",
        "coc": "YES",
        "brand": "LONKING",
        "year": 2022,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "4/2/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 7,
        "machine": "5 Ton Forklift",
        "regNo": "51216",
        "coc": "YES",
        "brand": "HELI",
        "year": 2013,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/28/2023",
        "certificationBody": "Dawis"
    },
    {
        "id": 8,
        "machine": "5 Ton Forklift",
        "regNo": "15050",
        "coc": "YES",
        "brand": "TCM",
        "year": 2015,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "7/22/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 9,
        "machine": "5 Ton Forklift",
        "regNo": "44177",
        "coc": "YES",
        "brand": "Toyota",
        "year": 2017,
        "istimaraExpiry": "8/13/2025",
        "insuranceExpiry": "8/22/2025",
        "tpcExpiry": "8/26/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 10,
        "machine": "5 Ton Forklift",
        "regNo": "44182",
        "coc": "YES",
        "brand": "Toyota",
        "year": 2016,
        "istimaraExpiry": "8/12/2025",
        "insuranceExpiry": "8/22/2025",
        "tpcExpiry": "6/8/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 11,
        "machine": "5 Ton Forklift",
        "regNo": "72484",
        "coc": "YES",
        "brand": "Zoomlion",
        "year": 2021,
        "istimaraExpiry": "8/25/2025",
        "insuranceExpiry": "9/12/2025",
        "tpcExpiry": "6/23/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 12,
        "machine": "7 Ton Forklift",
        "regNo": "36699",
        "coc": "YES",
        "brand": "HELI",
        "year": 2016,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/20/2026",
        "tpcExpiry": "5/27/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 13,
        "machine": "7 Ton Forklift",
        "regNo": "36707",
        "coc": "YES",
        "brand": "HELI",
        "year": 2016,
        "istimaraExpiry": "12/16/2025",
        "insuranceExpiry": "1/3/2026",
        "tpcExpiry": "6/8/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 14,
        "machine": "7 Ton Forklift",
        "regNo": "43998",
        "coc": "YES",
        "brand": "HELI",
        "year": 2017,
        "istimaraExpiry": "6/22/2025",
        "insuranceExpiry": "7/12/2025",
        "tpcExpiry": "5/4/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 15,
        "machine": "10 Ton Forklift",
        "regNo": "21702",
        "coc": "YES",
        "brand": "HELI",
        "year": 2014,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "5/27/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 16,
        "machine": "10 Ton Forklift",
        "regNo": "62458",
        "coc": "YES",
        "brand": "HELI",
        "year": 2015,
        "istimaraExpiry": "6/9/2025",
        "insuranceExpiry": "6/9/2025",
        "tpcExpiry": "8/26/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 17,
        "machine": "10 Ton Forklift",
        "regNo": "47526",
        "coc": "YES",
        "brand": "HELI",
        "year": 2016,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "5/4/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 18,
        "machine": "10 Ton Forklift",
        "regNo": "68515",
        "coc": "YES",
        "brand": "HELI",
        "year": 2019,
        "istimaraExpiry": "6/2/2025",
        "insuranceExpiry": "7/1/2025",
        "tpcExpiry": "5/13/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 19,
        "machine": "10 Ton Forklift",
        "regNo": "76023",
        "coc": "YES",
        "brand": "HELI",
        "year": 2023,
        "istimaraExpiry": "6/22/2025",
        "insuranceExpiry": "7/19/2025",
        "tpcExpiry": "6/15/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 20,
        "machine": "10 Ton Forklift",
        "regNo": "76116",
        "coc": "YES",
        "brand": "HELI",
        "year": 2023,
        "istimaraExpiry": "7/7/2025",
        "insuranceExpiry": "7/7/2025",
        "tpcExpiry": "6/21/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 21,
        "machine": "10 Ton Forklift",
        "regNo": "77269",
        "coc": "YES",
        "brand": "HELI",
        "year": 2024,
        "istimaraExpiry": "2/15/2026",
        "insuranceExpiry": "2/27/2026",
        "tpcExpiry": "8/12/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 22,
        "machine": "10 Ton Forklift",
        "regNo": "77371",
        "coc": "YES",
        "brand": "HELI",
        "year": 2024,
        "istimaraExpiry": "3/18/2026",
        "insuranceExpiry": "3/31/2026",
        "tpcExpiry": "9/5/2025",
        "certificationBody": " "
    },
    {
        "id": 23,
        "machine": "10 Ton Forklift",
        "regNo": "77373",
        "coc": "YES",
        "brand": "HELI",
        "year": 2024,
        "istimaraExpiry": "3/18/2026",
        "insuranceExpiry": "3/31/2026",
        "tpcExpiry": "9/8/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 24,
        "machine": "10 Ton Forklift",
        "regNo": "78132",
        "coc": "YES",
        "brand": "HELI",
        "year": 2025,
        "istimaraExpiry": "10/8/2025",
        "insuranceExpiry": "10/9/2025",
        "tpcExpiry": "9/24/2025",
        "certificationBody": "Arsath"
    },
    {
        "id": 25,
        "machine": "10 Ton Forklift",
        "regNo": "78133",
        "coc": "YES",
        "brand": "HELI",
        "year": 2025,
        "istimaraExpiry": "10/9/2025",
        "insuranceExpiry": "10/9/2025",
        "tpcExpiry": "9/24/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 26,
        "machine": "10 Ton Forklift",
        "regNo": "78445",
        "coc": "YES",
        "brand": "HELI",
        "year": 2025,
        "istimaraExpiry": "11/26/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "5/27/2025",
        "certificationBody": "Tej Pandy"
    },
    {
        "id": 27,
        "machine": "10 Ton Forklift",
        "regNo": "78447",
        "coc": "YES",
        "brand": "HELI",
        "year": 2025,
        "istimaraExpiry": "11/26/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "5/27/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 28,
        "machine": "10 Ton Forklift",
        "regNo": "78357",
        "coc": "YES",
        "brand": "ZOOMLION",
        "year": 2025,
        "istimaraExpiry": "1/22/2026",
        "insuranceExpiry": "1/22/2026",
        "tpcExpiry": "7/22/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 29,
        "machine": "10 Ton Forklift",
        "regNo": "78784",
        "coc": "YES",
        "brand": "BAOLI",
        "year": 2025,
        "istimaraExpiry": "2/25/2026",
        "insuranceExpiry": "2/25/2026",
        "tpcExpiry": "9/5/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 30,
        "machine": "15 Ton Forklift",
        "regNo": "78129",
        "coc": "YES",
        "brand": "ZOOMLION",
        "year": 2025,
        "istimaraExpiry": "10/9/2025",
        "insuranceExpiry": "10/9/2025",
        "tpcExpiry": "9/26/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 31,
        "machine": "16 Ton Forklift",
        "regNo": "78356",
        "coc": "YES",
        "brand": "ZOOMLION",
        "year": 2025,
        "istimaraExpiry": "1/22/2026",
        "insuranceExpiry": "1/22/2026",
        "tpcExpiry": "7/22/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 32,
        "machine": "Skid Loader",
        "regNo": "54470",
        "coc": "YES",
        "brand": "JCB",
        "year": 2016,
        "istimaraExpiry": "8/12/2025",
        "insuranceExpiry": "8/23/2025",
        "tpcExpiry": "9/3/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 33,
        "machine": "Skid Loader",
        "regNo": "65701",
        "coc": "YES",
        "brand": "HYUNDAI",
        "year": 2017,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "10/16/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 34,
        "machine": "Skid Loader",
        "regNo": "47326",
        "coc": "YES",
        "brand": "CASE",
        "year": 2018,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "10/13/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 35,
        "machine": "Skid Loader",
        "regNo": "70670",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/11/2026",
        "tpcExpiry": "2/8/2026",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 36,
        "machine": "Skid Loader",
        "regNo": "70671",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/20/2026",
        "tpcExpiry": "6/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 37,
        "machine": "Skid Loader",
        "regNo": "74991",
        "coc": "YES",
        "brand": "JCB",
        "year": 2022,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "11/4/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 38,
        "machine": "Skid Loader",
        "regNo": "74992",
        "coc": "YES",
        "brand": "JCB",
        "year": 2022,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "5/5/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 39,
        "machine": "Skid Loader",
        "regNo": "75012",
        "coc": "YES",
        "brand": "JCB",
        "year": 2022,
        "istimaraExpiry": "10/19/2025",
        "insuranceExpiry": "11/14/2025",
        "tpcExpiry": "9/18/2025",
        "certificationBody": "Ajmal"
    },
    {
        "id": 40,
        "machine": "Skid Loader",
        "regNo": "75013",
        "coc": "YES",
        "brand": "JCB",
        "year": 2022,
        "istimaraExpiry": "11/23/2025",
        "insuranceExpiry": "11/23/2025",
        "tpcExpiry": "11/27/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 41,
        "machine": "Skid Loader",
        "regNo": "77451",
        "coc": "YES",
        "brand": "JCB",
        "year": 2023,
        "istimaraExpiry": "4/28/2025",
        "insuranceExpiry": "4/28/2025",
        "tpcExpiry": "9/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 42,
        "machine": "Skid Loader",
        "regNo": "77452",
        "coc": "YES",
        "brand": "JCB",
        "year": 2023,
        "istimaraExpiry": "4/28/2025",
        "insuranceExpiry": "4/28/2025",
        "tpcExpiry": "10/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 43,
        "machine": "Skid Loader",
        "regNo": "78391",
        "coc": "YES",
        "brand": "JCB",
        "year": 2024,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/11/2025",
        "tpcExpiry": "5/16/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 44,
        "machine": "Skid Loader",
        "regNo": "78392",
        "coc": "YES",
        "brand": "JCB",
        "year": 2024,
        "istimaraExpiry": "11/12/2025",
        "insuranceExpiry": "11/12/2025",
        "tpcExpiry": "5/16/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 45,
        "machine": "Skid Loader",
        "regNo": "78393",
        "coc": "YES",
        "brand": "JCB",
        "year": 2024,
        "istimaraExpiry": "11/12/2025",
        "insuranceExpiry": "11/12/2025",
        "tpcExpiry": "5/16/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 46,
        "machine": "Backhoe Loader",
        "regNo": "66774",
        "coc": "YES",
        "brand": "JCB",
        "year": 2018,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "7/5/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 47,
        "machine": "Backhoe Loader",
        "regNo": "66775",
        "coc": "YES",
        "brand": "JCB",
        "year": 2018,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/25/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 48,
        "machine": "Backhoe Loader",
        "regNo": "66776",
        "coc": "YES",
        "brand": "JCB",
        "year": 2018,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 49,
        "machine": "Backhoe Loader",
        "regNo": "66777",
        "coc": "YES",
        "brand": "JCB",
        "year": 2018,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/25/2025",
        "certificationBody": "Thivari"
    },
    {
        "id": 50,
        "machine": "Backhoe Loader",
        "regNo": "67822",
        "coc": "YES",
        "brand": "CASE",
        "year": 2020,
        "istimaraExpiry": "8/12/2025",
        "insuranceExpiry": "8/21/2025",
        "tpcExpiry": "9/6/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 51,
        "machine": "Backhoe Loader",
        "regNo": "67823",
        "coc": "YES",
        "brand": "CASE",
        "year": 2020,
        "istimaraExpiry": "8/2/2025",
        "insuranceExpiry": "8/6/2025",
        "tpcExpiry": "9/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 52,
        "machine": "Backhoe Loader",
        "regNo": "68115",
        "coc": "YES",
        "brand": "CASE",
        "year": 2020,
        "istimaraExpiry": "9/15/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "8/12/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 53,
        "machine": "Backhoe Loader",
        "regNo": "68116",
        "coc": "YES",
        "brand": "CASE",
        "year": 2020,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/3/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 54,
        "machine": "Backhoe Loader",
        "regNo": "68728",
        "coc": "YES",
        "brand": "JCB",
        "year": 2020,
        "istimaraExpiry": "6/22/2025",
        "insuranceExpiry": "7/2/2025",
        "tpcExpiry": "11/27/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 55,
        "machine": "Backhoe Loader",
        "regNo": "68729",
        "coc": "YES",
        "brand": "JCB",
        "year": 2020,
        "istimaraExpiry": "6/22/2025",
        "insuranceExpiry": "7/2/2025",
        "tpcExpiry": "12/21/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 56,
        "machine": "Backhoe Loader",
        "regNo": "69557",
        "coc": "YES",
        "brand": "JCB",
        "year": 2020,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/8/2025",
        "certificationBody": "Jaman Singh"
    },
    {
        "id": 57,
        "machine": "Backhoe Loader",
        "regNo": "69558",
        "coc": "YES",
        "brand": "JCB",
        "year": 2020,
        "istimaraExpiry": "9/17/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/30/2025",
        "certificationBody": "Dumind"
    },
    {
        "id": 58,
        "machine": "Backhoe Loader",
        "regNo": "72201",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "7/10/2025",
        "insuranceExpiry": "7/10/2025",
        "tpcExpiry": "9/26/2025",
        "certificationBody": "Love Preeth Sing"
    },
    {
        "id": 59,
        "machine": "Backhoe Loader",
        "regNo": "72202",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "7/10/2025",
        "insuranceExpiry": "7/10/2025",
        "tpcExpiry": "7/5/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 60,
        "machine": "Backhoe Loader",
        "regNo": "72203",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "7/10/2025",
        "insuranceExpiry": "7/10/2025",
        "tpcExpiry": "6/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 61,
        "machine": "Backhoe Loader",
        "regNo": "72204",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "7/31/2025",
        "insuranceExpiry": "7/31/2025",
        "tpcExpiry": "7/6/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 62,
        "machine": "Telehandler",
        "regNo": "27160",
        "coc": "YES",
        "brand": "JCB",
        "year": 2015,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/19/2026",
        "tpcExpiry": "6/21/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 63,
        "machine": "Telehandler",
        "regNo": "61188",
        "coc": "YES",
        "brand": "JCB",
        "year": 2015,
        "istimaraExpiry": "6/4/2025",
        "insuranceExpiry": "6/3/2025",
        "tpcExpiry": "6/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 64,
        "machine": "Telehandler",
        "regNo": "45541",
        "coc": "YES",
        "brand": "CASE",
        "year": 2017,
        "istimaraExpiry": "12/16/2025",
        "insuranceExpiry": "1/13/2026",
        "tpcExpiry": "9/5/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 65,
        "machine": "Telehandler",
        "regNo": "45542",
        "coc": "YES",
        "brand": "CASE",
        "year": 2017,
        "istimaraExpiry": "12/16/2025",
        "insuranceExpiry": "1/13/2026",
        "tpcExpiry": "8/17/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 66,
        "machine": "Telehandler",
        "regNo": "66564",
        "coc": "YES",
        "brand": "CASE",
        "year": 2018,
        "istimaraExpiry": "3/18/2026",
        "insuranceExpiry": "4/16/2026",
        "tpcExpiry": "5/27/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 67,
        "machine": "Telehandler",
        "regNo": "68731",
        "coc": "YES",
        "brand": "JCB",
        "year": 2020,
        "istimaraExpiry": "6/9/2025",
        "insuranceExpiry": "6/9/2025",
        "tpcExpiry": "6/21/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 68,
        "machine": "Telehandler",
        "regNo": "68732",
        "coc": "YES",
        "brand": "JCB",
        "year": 2020,
        "istimaraExpiry": "6/9/2025",
        "insuranceExpiry": "6/9/2025",
        "tpcExpiry": "8/26/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 69,
        "machine": "Telehandler",
        "regNo": "68733",
        "coc": "YES",
        "brand": "JCB",
        "year": 2020,
        "istimaraExpiry": "6/9/2025",
        "insuranceExpiry": "6/9/2025",
        "tpcExpiry": "5/4/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 70,
        "machine": "Telehandler",
        "regNo": "70669",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/11/2026",
        "tpcExpiry": "8/12/2025",
        "certificationBody": "Jahir Miya"
    },
    {
        "id": 71,
        "machine": "Telehandler",
        "regNo": "72097",
        "coc": "YES",
        "brand": "JCB",
        "year": 2021,
        "istimaraExpiry": "7/31/2025",
        "insuranceExpiry": "7/31/2025",
        "tpcExpiry": "8/12/2025",
        "certificationBody": "Keshav"
    },
    {
        "id": 72,
        "machine": "Mini Excavator",
        "regNo": "69861",
        "coc": "YES",
        "brand": "HYUNDAI",
        "year": 2020,
        "istimaraExpiry": "7/31/2025",
        "insuranceExpiry": "7/31/2025",
        "tpcExpiry": "8/5/2025",
        "certificationBody": "Talvinder Sing"
    },
    {
        "id": 73,
        "machine": "Mini Excavator",
        "regNo": "69862",
        "coc": "YES",
        "brand": "HYUNDAI",
        "year": 2020,
        "istimaraExpiry": "7/31/2025",
        "insuranceExpiry": "7/31/2025",
        "tpcExpiry": "8/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 74,
        "machine": "22 Ton Crawler Excavator",
        "regNo": "70892",
        "coc": "YES",
        "brand": "Doosan",
        "year": 2021,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/20/2026",
        "tpcExpiry": "10/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 75,
        "machine": "22 Ton Crawler Excavator",
        "regNo": "70893",
        "coc": "YES",
        "brand": "Doosan",
        "year": 2021,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/19/2026",
        "tpcExpiry": "8/26/2025",
        "certificationBody": "Ramesh thing"
    },
    {
        "id": 76,
        "machine": "20 Ton Wheel Excavator",
        "regNo": "46941",
        "coc": "YES",
        "brand": "HYUNDAI",
        "year": 2018,
        "istimaraExpiry": "7/22/2025",
        "insuranceExpiry": "8/14/2025",
        "tpcExpiry": "9/8/2025",
        "certificationBody": " "
    },
    {
        "id": 77,
        "machine": "20 Ton Wheel Excavator",
        "regNo": "68978",
        "coc": "YES",
        "brand": "HYUNDAI",
        "year": 2020,
        "istimaraExpiry": "6/22/2025",
        "insuranceExpiry": "7/2/2025",
        "tpcExpiry": "6/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 78,
        "machine": "20 Ton Wheel Excavator",
        "regNo": "68979",
        "coc": "YES",
        "brand": "HYUNDAI",
        "year": 2020,
        "istimaraExpiry": "6/22/2025",
        "insuranceExpiry": "7/2/2025",
        "tpcExpiry": "6/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 79,
        "machine": "20 Ton Wheel Excavator",
        "regNo": "46942",
        "coc": "YES",
        "brand": "HYUNDAI",
        "year": 2018,
        "istimaraExpiry": "8/2/2025",
        "insuranceExpiry": "8/8/2025",
        "tpcExpiry": "9/5/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 80,
        "machine": "30 Ton Crawler Excavator",
        "regNo": "67339",
        "coc": "YES",
        "brand": "JCB",
        "year": 2018,
        "istimaraExpiry": "10/1/2025",
        "insuranceExpiry": "10/1/2025",
        "tpcExpiry": "9/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 81,
        "machine": "30 Ton Crawler Excavator",
        "regNo": "67340",
        "coc": "YES",
        "brand": "JCB",
        "year": 2018,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "9/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 82,
        "machine": "Wheel Loader",
        "regNo": "63259",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2016,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/11/2026",
        "tpcExpiry": "10/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 83,
        "machine": "Wheel Loader",
        "regNo": "70124",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2021,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/11/2026",
        "tpcExpiry": "7/6/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 84,
        "machine": "Wheel Loader",
        "regNo": "70125",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2021,
        "istimaraExpiry": "12/16/2025",
        "insuranceExpiry": "1/13/2026",
        "tpcExpiry": "7/24/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 85,
        "machine": "Wheel Loader",
        "regNo": "70126",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2021,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/11/2026",
        "tpcExpiry": "7/17/2025",
        "certificationBody": " "
    },
    {
        "id": 86,
        "machine": "Wheel Loader",
        "regNo": "71051",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2021,
        "istimaraExpiry": "6/9/2025",
        "insuranceExpiry": "6/9/2025",
        "tpcExpiry": "6/4/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 87,
        "machine": "Wheel Loader",
        "regNo": "72738",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2022,
        "istimaraExpiry": "9/18/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/25/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 88,
        "machine": "Wheel Loader",
        "regNo": "71056",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2022,
        "istimaraExpiry": "9/18/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/25/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 89,
        "machine": "Wheel Loader",
        "regNo": "72129",
        "coc": "YES",
        "brand": "LiuGong",
        "year": 2022,
        "istimaraExpiry": "11/11/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "10/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 90,
        "machine": "60 Ton Mobile Crane",
        "regNo": "45838",
        "coc": "YES",
        "brand": "SANY",
        "year": 2018,
        "istimaraExpiry": "12/28/2025",
        "insuranceExpiry": "12/28/2025",
        "tpcExpiry": "8/24/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 91,
        "machine": "60 Ton Mobile Crane",
        "regNo": "67973",
        "coc": "YES",
        "brand": "SANY",
        "year": 2018,
        "istimaraExpiry": "10/5/2025",
        "insuranceExpiry": "10/29/2025",
        "tpcExpiry": "9/23/2025",
        "certificationBody": "Malkit Singh"
    },
    {
        "id": 92,
        "machine": "30 Ton Mobile Crane",
        "regNo": "68154",
        "coc": "YES",
        "brand": "SANY",
        "year": 2020,
        "istimaraExpiry": "11/23/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "7/8/2025",
        "certificationBody": "Indica"
    },
    {
        "id": 93,
        "machine": "30 Ton Mobile Crane",
        "regNo": "76272",
        "coc": "YES",
        "brand": "SANY",
        "year": 2022,
        "istimaraExpiry": "8/10/2025",
        "insuranceExpiry": "8/10/2025",
        "tpcExpiry": "8/3/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 94,
        "machine": "30 Ton Mobile Crane",
        "regNo": "76273",
        "coc": "YES",
        "brand": "SANY",
        "year": 2022,
        "istimaraExpiry": "8/3/2025",
        "insuranceExpiry": "8/3/2025",
        "tpcExpiry": "7/17/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 95,
        "machine": "60 Ton Mobile Crane",
        "regNo": "75865",
        "coc": "YES",
        "brand": "SANY",
        "year": 2023,
        "istimaraExpiry": "4/5/2026",
        "insuranceExpiry": "4/20/2026",
        "tpcExpiry": "8/5/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 96,
        "machine": "60 Ton Mobile Crane",
        "regNo": "78516",
        "coc": "YES",
        "brand": "SANY",
        "year": 2024,
        "istimaraExpiry": "12/9/2025",
        "insuranceExpiry": "12/9/2025",
        "tpcExpiry": "7/31/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 97,
        "machine": "60 Ton Mobile Crane",
        "regNo": "78523",
        "coc": "YES",
        "brand": "SANY",
        "year": 2025,
        "istimaraExpiry": "2/9/2026",
        "insuranceExpiry": "2/9/2026",
        "tpcExpiry": "8/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 98,
        "machine": "80 Ton Mobile Crane",
        "regNo": "75864",
        "coc": "YES",
        "brand": "SANY",
        "year": 2023,
        "istimaraExpiry": "4/5/2026",
        "insuranceExpiry": "4/29/2026",
        "tpcExpiry": "5/3/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 99,
        "machine": "80 Ton Mobile Crane",
        "regNo": "75866",
        "coc": "YES",
        "brand": "SANY",
        "year": 2023,
        "istimaraExpiry": "3/22/2026",
        "insuranceExpiry": "4/6/2026",
        "tpcExpiry": "4/20/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 100,
        "machine": "80 Ton Mobile Crane",
        "regNo": "78325",
        "coc": "YES",
        "brand": "SANY",
        "year": 2025,
        "istimaraExpiry": "10/22/2025",
        "insuranceExpiry": "10/22/2025",
        "tpcExpiry": "4/14/2025",
        "certificationBody": "TUV SUD QP STD"
    },
    {
        "id": 101,
        "machine": "80 Ton Mobile Crane",
        "regNo": "78324",
        "coc": "YES",
        "brand": "SANY",
        "year": 2025,
        "istimaraExpiry": "10/22/2025",
        "insuranceExpiry": "10/22/2025",
        "tpcExpiry": "7/28/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 102,
        "machine": "3 Ton Roller",
        "regNo": "70760",
        "coc": "YES",
        "brand": "BOMAG",
        "year": 2020,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "2/20/2026",
        "tpcExpiry": "3/5/2026",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 103,
        "machine": "3 Ton Roller",
        "regNo": "70770",
        "coc": "YES",
        "brand": "BOMAG",
        "year": 2020,
        "istimaraExpiry": "1/31/2026",
        "insuranceExpiry": "2/20/2026",
        "tpcExpiry": "8/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 104,
        "machine": "10 Ton Roller",
        "regNo": "63438",
        "coc": "YES",
        "brand": "BOMAG",
        "year": 2016,
        "istimaraExpiry": "11/9/2025",
        "insuranceExpiry": "11/26/2025",
        "tpcExpiry": "6/21/2025",
        "certificationBody": " "
    },
    {
        "id": 105,
        "machine": "10 Ton Roller",
        "regNo": "43711",
        "coc": "YES",
        "brand": "BOMAG",
        "year": 2016,
        "istimaraExpiry": "6/22/2025",
        "insuranceExpiry": "6/22/2025",
        "tpcExpiry": "8/17/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 106,
        "machine": "3 Ton Boom Truck",
        "regNo": "239500",
        "coc": "",
        "brand": "MITS",
        "year": 2012,
        "istimaraExpiry": "10/18/2025",
        "insuranceExpiry": "11/4/2025",
        "tpcExpiry": "8/19/2024",
        "certificationBody": "Dawis"
    },
    {
        "id": 107,
        "machine": "10 Ton Boom Truck",
        "regNo": "310773",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2018,
        "istimaraExpiry": "5/14/2025",
        "insuranceExpiry": "6/8/2025",
        "tpcExpiry": "8/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 108,
        "machine": "12 Ton Boom Truck",
        "regNo": "281603",
        "coc": "",
        "brand": "UDTR",
        "year": 2025,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "1/27/2026",
        "tpcExpiry": "7/28/2025",
        "certificationBody": "Ibrahim"
    },
    {
        "id": 109,
        "machine": "12 Ton Boom Truck",
        "regNo": "105113",
        "coc": "",
        "brand": "UDTR",
        "year": 2025,
        "istimaraExpiry": "1/27/2026",
        "insuranceExpiry": "1/27/2026",
        "tpcExpiry": "8/13/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 110,
        "machine": "Mini Dump Truck",
        "regNo": "198331",
        "coc": "",
        "brand": "ISUZU",
        "year": 2024,
        "istimaraExpiry": "8/2/2025",
        "insuranceExpiry": "8/27/2025",
        "tpcExpiry": "7/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 111,
        "machine": "Dump Truck",
        "regNo": "237737",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2017,
        "istimaraExpiry": "3/2/2026",
        "insuranceExpiry": "3/16/2026",
        "tpcExpiry": "9/18/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 112,
        "machine": "Dump Truck",
        "regNo": "327738",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2017,
        "istimaraExpiry": "7/8/2025",
        "insuranceExpiry": "7/17/2025",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 113,
        "machine": "Dump Truck",
        "regNo": "281998",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2023,
        "istimaraExpiry": "4/20/2025",
        "insuranceExpiry": "4/20/2025",
        "tpcExpiry": "10/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 114,
        "machine": "Dump Truck",
        "regNo": "282062",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2023,
        "istimaraExpiry": "4/29/2025",
        "insuranceExpiry": "4/29/2025",
        "tpcExpiry": "10/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 115,
        "machine": "Dump Truck",
        "regNo": "282171",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2023,
        "istimaraExpiry": "4/27/2025",
        "insuranceExpiry": "4/27/2025",
        "tpcExpiry": "10/23/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 116,
        "machine": "Dump Truck",
        "regNo": "14651",
        "coc": "",
        "brand": "UD TRUCKS",
        "year": 2023,
        "istimaraExpiry": "9/21/2025",
        "insuranceExpiry": "10/4/2025",
        "tpcExpiry": "9/3/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 117,
        "machine": "Dump Truck",
        "regNo": "194159",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2024,
        "istimaraExpiry": "11/30/2025",
        "insuranceExpiry": "12/23/2025",
        "tpcExpiry": "5/27/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 118,
        "machine": "Dump Truck",
        "regNo": "195653",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2024,
        "istimaraExpiry": "12/16/2025",
        "insuranceExpiry": "12/23/2025",
        "tpcExpiry": "6/15/2025",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 119,
        "machine": "Dump Truck",
        "regNo": "138773",
        "coc": "GSO",
        "brand": "SINO TRUCK",
        "year": 2025,
        "istimaraExpiry": "2/9/2026",
        "insuranceExpiry": "2/9/2026",
        "tpcExpiry": "2/13/2026",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 120,
        "machine": "Dump Truck",
        "regNo": "138815",
        "coc": "GSO",
        "brand": "SINO TRUCK",
        "year": 2025,
        "istimaraExpiry": "2/9/2026",
        "insuranceExpiry": "2/9/2026",
        "tpcExpiry": "2/13/2026",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 121,
        "machine": "Dump Truck",
        "regNo": "139575",
        "coc": "GSO",
        "brand": "SINO TRUCK",
        "year": 2025,
        "istimaraExpiry": "2/18/2026",
        "insuranceExpiry": "2/18/2026",
        "tpcExpiry": "2/24/2026",
        "certificationBody": "TUV SUD"
    },
    {
        "id": 122,
        "machine": "15 Ton UD Recovery Truck",
        "regNo": "271261",
        "coc": "",
        "brand": "UD TRUCKS",
        "year": 2019,
        "istimaraExpiry": "10/27/2025",
        "insuranceExpiry": "11/29/2025",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 123,
        "machine": "Lowbed Trailer",
        "regNo": "195901/ 49649",
        "coc": "",
        "brand": "SINO TRUCK",
        "year": 2024,
        "istimaraExpiry": "9/15/2025",
        "insuranceExpiry": "9/15/2025",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 124,
        "machine": "HIACE",
        "regNo": "36450",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2015,
        "istimaraExpiry": "1/4/2026",
        "insuranceExpiry": "1/4/2026",
        "tpcExpiry": "NIL",
        "certificationBody": "Abdul Kais"
    },
    {
        "id": 125,
        "machine": "HIACE",
        "regNo": "218985",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2016,
        "istimaraExpiry": "7/6/2025",
        "insuranceExpiry": "7/6/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Risal"
    },
    {
        "id": 126,
        "machine": "HIACE",
        "regNo": "92373",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2023,
        "istimaraExpiry": "1/4/2026",
        "insuranceExpiry": "1/4/2026",
        "tpcExpiry": "NIL",
        "certificationBody": "Min Bahadoor"
    },
    {
        "id": 127,
        "machine": "PICKUP 1 ton",
        "regNo": "25997",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2016,
        "istimaraExpiry": "9/8/2025",
        "insuranceExpiry": "9/26/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Bal Bahadur"
    },
    {
        "id": 128,
        "machine": "Double Cabin Pickup",
        "regNo": "282660",
        "coc": "",
        "brand": "MITS",
        "year": 2014,
        "istimaraExpiry": "12/1/2025",
        "insuranceExpiry": "12/19/2025",
        "tpcExpiry": "",
        "certificationBody": "Santosh BK"
    },
    {
        "id": 129,
        "machine": "Double Cabin Pickup",
        "regNo": "312151",
        "coc": "",
        "brand": "MITS",
        "year": 2017,
        "istimaraExpiry": "8/2/2025",
        "insuranceExpiry": "8/21/2025",
        "tpcExpiry": "Motor pump TPC",
        "certificationBody": "RAZACK"
    },
    {
        "id": 130,
        "machine": "Pickup 1 ton",
        "regNo": "278051",
        "coc": "",
        "brand": "MITS",
        "year": 2019,
        "istimaraExpiry": "8/2/2025",
        "insuranceExpiry": "8/23/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Asaru"
    },
    {
        "id": 131,
        "machine": "3 Ton Double Cabin Pickup",
        "regNo": "278405",
        "coc": "",
        "brand": "MITS",
        "year": 2019,
        "istimaraExpiry": "9/8/2025",
        "insuranceExpiry": "9/24/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "jithin"
    },
    {
        "id": 132,
        "machine": "3 Ton Double Cabin Pickup",
        "regNo": "30931",
        "coc": "",
        "brand": "MITSUBISHI",
        "year": 2022,
        "istimaraExpiry": "11/9/2025",
        "insuranceExpiry": "11/9/2025",
        "tpcExpiry": "NIL",
        "certificationBody": ""
    },
    {
        "id": 133,
        "machine": "1 Ton Double Cabin Pickup",
        "regNo": "92389",
        "coc": "",
        "brand": "TOYOTA HILUX",
        "year": 2022,
        "istimaraExpiry": "1/4/2026",
        "insuranceExpiry": "1/4/2026",
        "tpcExpiry": "NIL",
        "certificationBody": "hamsa"
    },
    {
        "id": 134,
        "machine": "3 Ton Double Cabin Pickup",
        "regNo": "197300",
        "coc": "",
        "brand": "MITSUBISHI",
        "year": 2022,
        "istimaraExpiry": "12/29/2025",
        "insuranceExpiry": "1/10/2026",
        "tpcExpiry": "NIL",
        "certificationBody": ""
    },
    {
        "id": 135,
        "machine": "3 Ton Double Cabin Pickup",
        "regNo": "197304",
        "coc": "",
        "brand": "MITSUBISHI",
        "year": 2022,
        "istimaraExpiry": "12/28/2025",
        "insuranceExpiry": "12/28/2025",
        "tpcExpiry": "6/30/2025",
        "certificationBody": "sanil / Foysel"
    },
    {
        "id": 136,
        "machine": "4  Ton Single Cabin Pickup",
        "regNo": "44503",
        "coc": "",
        "brand": "ISUZU",
        "year": 2024,
        "istimaraExpiry": "10/20/2025",
        "insuranceExpiry": "11/5/2025",
        "tpcExpiry": "11/3/2025",
        "certificationBody": "Robert"
    },
    {
        "id": 137,
        "machine": "4  Ton Single Cabin Pickup",
        "regNo": "224483",
        "coc": "",
        "brand": "ISUZU",
        "year": 2025,
        "istimaraExpiry": "1/20/2026",
        "insuranceExpiry": "1/20/2026",
        "tpcExpiry": "",
        "certificationBody": "Jageshor"
    },
    {
        "id": 138,
        "machine": "1 Ton Double Cabin Pickup",
        "regNo": "224425",
        "coc": "",
        "brand": "ISUZU",
        "year": 2024,
        "istimaraExpiry": "1/20/2026",
        "insuranceExpiry": "1/20/2026",
        "tpcExpiry": "",
        "certificationBody": "Raju"
    },
    {
        "id": 139,
        "machine": "EICHER - BUS",
        "regNo": "51048",
        "coc": "",
        "brand": "EICHER",
        "year": 2020,
        "istimaraExpiry": "6/19/2025",
        "insuranceExpiry": "6/19/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Bandari"
    },
    {
        "id": 140,
        "machine": "FORTUNER",
        "regNo": "707937",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2016,
        "istimaraExpiry": "3/5/2026",
        "insuranceExpiry": "3/5/2026",
        "tpcExpiry": "NIL",
        "certificationBody": "SURESH"
    },
    {
        "id": 141,
        "machine": "LEXUS",
        "regNo": "106808",
        "coc": "",
        "brand": "Lexus",
        "year": 2017,
        "istimaraExpiry": "10/30/2025",
        "insuranceExpiry": "10/30/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Shaheen Sir"
    },
    {
        "id": 142,
        "machine": "LEXUS",
        "regNo": "783183",
        "coc": "",
        "brand": "Lexus",
        "year": 2019,
        "istimaraExpiry": "10/7/2025",
        "insuranceExpiry": "10/7/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Kamal sir"
    },
    {
        "id": 143,
        "machine": "INNOVA",
        "regNo": "233047",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2020,
        "istimaraExpiry": "10/6/2025",
        "insuranceExpiry": "10/11/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Sruthin"
    },
    {
        "id": 144,
        "machine": "INNOVA",
        "regNo": "817079",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2020,
        "istimaraExpiry": "10/7/2025",
        "insuranceExpiry": "10/22/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "jaleel ka"
    },
    {
        "id": 145,
        "machine": "RANGE ROVER",
        "regNo": "845375",
        "coc": "",
        "brand": "Land Rover",
        "year": 2020,
        "istimaraExpiry": "8/16/2025",
        "insuranceExpiry": "8/16/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Kamal sir wife"
    },
    {
        "id": 146,
        "machine": "Mercedes-Benz",
        "regNo": "546469",
        "coc": "",
        "brand": "Benz",
        "year": 2021,
        "istimaraExpiry": "2/27/2026",
        "insuranceExpiry": "2/26/2026",
        "tpcExpiry": "NIL",
        "certificationBody": "Shaheen Sir"
    },
    {
        "id": 147,
        "machine": "Rush",
        "regNo": "498319",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2022,
        "istimaraExpiry": "12/7/2025",
        "insuranceExpiry": "12/7/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Arsath"
    },
    {
        "id": 148,
        "machine": "INNOVA",
        "regNo": "336042",
        "coc": "",
        "brand": "INNOVA",
        "year": 2024,
        "istimaraExpiry": "11/10/2025",
        "insuranceExpiry": "11/10/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Arsath"
    },
    {
        "id": 149,
        "machine": "KIA SPORTAGE",
        "regNo": "604866",
        "coc": "",
        "brand": "KIA",
        "year": 2024,
        "istimaraExpiry": "4/28/2025",
        "insuranceExpiry": "4/28/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Malik"
    },
    {
        "id": 150,
        "machine": "Double Cabin Pickup",
        "regNo": "336358",
        "coc": "",
        "brand": "FOTON",
        "year": 2024,
        "istimaraExpiry": "6/23/2025",
        "insuranceExpiry": "6/23/2025",
        "tpcExpiry": "NIL",
        "certificationBody": "Firoz"
    },
    {
        "id": 151,
        "machine": "Corolla",
        "regNo": "963534",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2025,
        "istimaraExpiry": "1/22/2026",
        "insuranceExpiry": "1/22/2026",
        "tpcExpiry": "NIL",
        "certificationBody": "Roshan Sha"
    },
    {
        "id": 152,
        "machine": "Corolla",
        "regNo": "963536",
        "coc": "",
        "brand": "TOYOTA",
        "year": 2025,
        "istimaraExpiry": "1/22/2026",
        "insuranceExpiry": "1/22/2026",
        "tpcExpiry": "NIL",
        "certificationBody": "Jaleel PRO"
    },
    {
        "id": 153,
        "machine": "Plate Compactor 225 kg",
        "regNo": "101692683943",
        "coc": "",
        "brand": "BOMAG",
        "year": 2018,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "5/22/2025",
        "certificationBody": "DNV"
    },
    {
        "id": 154,
        "machine": "Plate Compactor 225 kg",
        "regNo": "101692683941",
        "coc": "",
        "brand": "BOMAG",
        "year": 2018,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 155,
        "machine": "Plate Compactor 225 kg",
        "regNo": "101692683949",
        "coc": "",
        "brand": "BOMAG",
        "year": 2018,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "5/9/2025",
        "certificationBody": "DNV"
    },
    {
        "id": 156,
        "machine": "Plate Compactor 225 kg",
        "regNo": "101692683945",
        "coc": "",
        "brand": "BOMAG",
        "year": 2018,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 157,
        "machine": "Plate Compactor 225 kg",
        "regNo": "101692683950",
        "coc": "",
        "brand": "BOMAG",
        "year": 2018,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 158,
        "machine": "80 Ton Mobile Crane",
        "regNo": "78862",
        "coc": "YES",
        "brand": "ZOOMLION",
        "year": 2025,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 159,
        "machine": "80 Ton Mobile Crane",
        "regNo": "78863",
        "coc": "YES",
        "brand": "ZOOMLION",
        "year": 2025,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    {
        "id": 160,
        "machine": "110 Ton Mobile Crane",
        "regNo": "78971",
        "coc": "YES",
        "brand": "SANY",
        "year": 2025,
        "istimaraExpiry": "",
        "insuranceExpiry": "",
        "tpcExpiry": "",
        "certificationBody": ""
    },
    // {
    //     "id": 159,
    //     "machine": "Zoomlion 80 Ton Crane",
    //     "regNo": "70155",
    //     "coc": "YES",
    //     "brand": "ZOOMLION",
    //     "year": 2025,
    //     "istimaraExpiry": "",
    //     "insuranceExpiry": "",
    //     "tpcExpiry": "",
    //     "certificationBody": "Muhammad Gul"
    // }
]

module.exports = equipments}